# -*- coding: utf-8 -*-
"""generative_ai_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CA0XPPacxxQt9PGJAJXKnnpOACAUW6Ik
"""

from dataset import generate_synthetic_dataset
from training import train_model
from testing import test_model

from generate_synthetic_dataset import setup_pipeline, generate_dataset, preview_images
from train_model import train_model
from test_model import test_model, compute_ssim


# Initialize the Stable Diffusion pipeline
pipe = setup_pipeline()

# Generate the dataset
generate_dataset(pipe, num_pairs=100, output_dir="dataset/generated_faces")

preview_images(output_dir="/dataset/generated_faces", num_images=10)

train_model(dataset_dir="dataset/generated_faces")

# Load the test data
test_dataset = BeardedDataset(clean_shaven_dir="dataset/generated_faces",
                              bearded_dir="dataset/generated_faces",
                              transform=transform)
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)

# Validate the model
validate_model(model, test_loader)

# Example of SSIM calculation
ssim_value = compute_ssim(outputs[0], clean_shaven_images[0])
print(f"SSIM: {ssim_value}")





















